/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xarmaESUESI
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Bricolage_Grotesque } from 'next/font/google'
import { Syne } from 'next/font/google'

bricolage_grotesque({
  subsets: ['latin'],
  display: 'swap',
})

syne({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Login() {
  return (
    <main className="flex-1 py-12 px-6">
      <div className="flex justify-center">
        <div className="bg-[#1e293b] rounded-lg p-8 w-full max-w-md">
          <h2 className="text-3xl font-bold mb-4">Login</h2>
          <form>
            <div className="mb-4">
              <label className="block text-gray-400 mb-2" htmlFor="email">
                Email
              </label>
              <input
                className="bg-[#1e293b] border-[#4f46e5] border border-gray-200 rounded-md py-2 px-4 w-full focus:outline-none focus:ring focus:ring-[#4f46e5] dark:border-gray-800"
                id="email"
                placeholder="Enter your email"
                type="email"
              />
            </div>
            <div className="mb-4">
              <label className="block text-gray-400 mb-2" htmlFor="password">
                Password
              </label>
              <input
                className="bg-[#1e293b] border-[#4f46e5] border border-gray-200 rounded-md py-2 px-4 w-full focus:outline-none focus:ring focus:ring-[#4f46e5] dark:border-gray-800"
                id="password"
                placeholder="Enter your password"
                type="password"
              />
            </div>
            <button
              className="bg-[#4f46e5] text-white px-4 py-2 rounded-md hover:bg-[#4338ca] w-full"
              type="submit"
            >
              Login
            </button>
          </form>
          <div className="mt-4 text-center">
            <p className="text-gray-400">
              {"Don't have an account? "}
              <a className="text-[#4f46e5] hover:underline" href="#">
                Register
              </a>
            </p>
          </div>
        </div>
      </div>
    </main>
  );
}
