/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3gWycSxjXPE
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Bricolage_Grotesque } from 'next/font/google'
import { Syne } from 'next/font/google'

bricolage_grotesque({
  subsets: ['latin'],
  display: 'swap',
})

syne({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Image from "next/image";
import Logo from "./logo.jpeg";
import InterstellarTelescope from "./products-images/Interstellar Telescope.jpeg";
import GravityBoots from "./products-images/Gravity Boots.jpeg";
import InterplanetaryCommunicator from "./products-images/Interplanetary Communicator.jpeg";
import InterstellarSurvivalKit from "./products-images/Interstellar Survival Kit.jpeg";
import ProductsGrid from "./product-grid";

export function Main() {
  return (
    <main className="flex-1 py-12 px-6">
      <section className="mb-12" id="products">
        <h2 className="text-3xl font-bold mb-4">Featured Products</h2>
        <ProductsGrid />
      </section>
      <section className="mb-12" id="delivery">
        <h2 className="text-3xl font-bold mb-4">Delivery Information</h2>
        <div className="bg-[#1e293b] rounded-lg p-6">
          <h3 className="text-2xl font-bold mb-4">Rocket-Powered Delivery</h3>
          <p className="text-gray-400 mb-4">
            We use the latest in rocket technology to deliver your purchases to
            any planet in the solar system. Our fleet of high-speed rockets can
            reach even the most distant destinations in record time.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            <div>
              <h4 className="text-xl font-bold mb-2">Delivery Times</h4>
              <ul className="list-disc pl-6 text-gray-400">
                <li>Earth: 1-2 days</li>
                <li>Mars: 3-5 days</li>
                <li>Jupiter: 7-10 days</li>
                <li>Neptune: 14-21 days</li>
              </ul>
            </div>
            <div>
              <h4 className="text-xl font-bold mb-2">Delivery Costs</h4>
              <ul className="list-disc pl-6 text-gray-400">
                <li>Earth: $9.99</li>
                <li>Mars: $49.99</li>
                <li>Jupiter: $99.99</li>
                <li>Neptune: $199.99</li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      <section className="mb-12" id="about">
        <h2 className="text-3xl font-bold mb-4">How It Works</h2>
        <div className="bg-[#1e293b] rounded-lg p-6">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            <div>
              <h3 className="text-2xl font-bold mb-4">1. Select Your Items</h3>
              <p className="text-gray-400 mb-4">
                Browse our selection of interplanetary products and add the ones
                you want to your cart.
              </p>
            </div>
            <div>
              <h3 className="text-2xl font-bold mb-4">
                2. Choose Your Destination
              </h3>
              <p className="text-gray-400 mb-4">
                Specify the planet you want your items delivered to and review
                the delivery time and cost.
              </p>
            </div>
            <div>
              <h3 className="text-2xl font-bold mb-4">
                3. Complete Your Order
              </h3>
              <p className="text-gray-400 mb-4">
                Provide your payment information and confirm your order. We'll
                blast off your items as soon as possible.
              </p>
            </div>
            <div>
              <h3 className="text-2xl font-bold mb-4">
                4. Enjoy Your Purchase
              </h3>
              <p className="text-gray-400 mb-4">
                Sit back and relax while we deliver your items to your doorstep
                on your chosen planet.
              </p>
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
